theme: jekyll-theme-slate
title: Levi Basom
subtitle: STAT 184 Final Project
description: Feel free to browse the data csv files that I used for this project, view the Rmd file, and look at my notebook HTML file!
